version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  web:
    image: covid
    ports:
      - "80:5000"
    depends_on:
      - db