--- 
jobs: 
  aws-ecr/build-and-push-image: 
    account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
    aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
    aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
    create-repo: false
    dockerfile: Dockerfile
    path: "."
    profile-name: Covid
    region: AWS_REGION_ENV_VAR_NAME
    repo: covid
    tag: latest
  build: 
    docker: 
      - 
        environment: 
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          PGHOST: "127.0.0.1"
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
        image: "circleci/ruby:2.6.3-stretch-node"
      - 
        environment: 
          POSTGRES_DB: rails_blog
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: circleci-demo-ruby
        image: "circleci/postgres:9.5-alpine"
    parallelism: 1
    steps: 
      - checkout
      - 
        run: 
          command: "gem install bundler:2.1.4"
          name: "Install bundler"
      - 
        restore_cache: 
          keys: 
            - "covid-volunteers-{{ checksum \"Gemfile.lock\" }}"
            - covid-volunteers-
      - 
        run: 
          command: "bundle check --path vendor/bundle || bundle install --deployment"
          name: "Bundle Install"
      - 
        save_cache: 
          key: "covid-volunteers-{{ checksum \"Gemfile.lock\" }}"
          paths: 
            - vendor/bundle
      - 
        restore_cache: 
          keys: 
            - "covid-volunteers-yarn-{{ checksum \"yarn.lock\" }}"
            - covid-volunteers-yarn-
      - 
        run: 
          command: "yarn install --cache-folder ~/.cache/yarn"
          name: "Yarn Install"
      - 
        save_cache: 
          key: "covid-volunteers-yarn-{{ checksum \"yarn.lock\" }}"
          paths: 
            - ~/.cache/yarn
      - 
        store_test_results: 
          path: test_results
orbs: 
  aws-ecr: circleci/aws-ecr@6.8.0
  ruby: circleci/ruby@0.1.2
version: 2.1
workflows: 
  build-and-deploy: 
    jobs: 
      - build
      - aws-ecr/build-and-push-image: 
          requires: 
            - build
  version: 2