project_groups:
  - name: Prevention
    body: Inform, reduce, and control the spread of the outbreak.
    project_types:
      - Track the outbreak
      - Reduce spread
    color: orange
  - name: Medical
    body: Support our overwhelmed health systems with medical innovation.
    project_types:
      - Scale testing
      - Medical facilities
      - Medical equipments
      - Treatment R&D
    color: indigo
  - name: Community
    body: Work together to help our stressed communities.
    project_types:
      - E-Learning
      - Job placement
      - Mental health
      - Help out communities
      - Map volunteers to needs
      - News and information
      - Social giving
    color: blue

global_announcements:
  - title: Helpful resources for your projects
    sub_title: We wrote a playbook on how to manage volunteers, had some amazing panels, and gathered some deals for you.
    cta_text: Browse resources
    cta_url: /offers

events:
  - title: HWC Volunteer Playbook
    sub_title: A short guide created by our team to help you successfully manager your project and volunteers!
    cta_text: Download playbook
    cta_url: https://docs.google.com/document/d/1f_-g893NGawa5n4KyDw6zjrocO2VBS5b2siQIZ6csY0/view
  - title: Webinar on Philanthropic Fundraising
    sub_title: Jennifer Pisansky has 10 years of experience in philanthropic fundraising and talks about raising from foundations.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/share/3dZaM6vJy1NJfp3c2UHkfa8oQL-7T6a82yRN-fsOmkl9jfRS3GPg-L-gS4Y9zJu3
  - title: Webinar on How to Scale Volunteers
    sub_title: Glen Moriarty, founder of 7cups on how he manages 320k volunteers.
    cta_text: View recording
    cta_url: https://openai.zoom.us/rec/play/vZN-dbuq-m03TNKSsASDAfEtW466J6qs1XQWrvtYxRvmU3QDNVv0NLJGYbffjdiMo1gf68qHVnbe2mOi?continueMode=true
  - title: Webinar on Picking Ideas to Work On
    sub_title: Ivan Gayton, former Head of Mission and Board Member at Doctors without Border, talks about building technology for humanitarian/emergency purposes.
    cta_text: View recording
    cta_url: https://zoom.us/rec/share/5sttA5fAsWxLT6_Nx2-Yd7IEDqfuaaa823JI8_tcyUYSZzIbgvNy717m1UGGegEf

upcoming_events:
  - title: Project Owners Office Hours led by Jamie Wilkinson
    sub_title: Thursday, April 9th 4pm-5pm PST | <a href="https://docs.google.com/spreadsheets/d/1TBW8F29202kdKs8kclI-3SZHJMZ6QjYW0l0UfIyFnKc/edit#gid=0" class="text-indigo-600 font-bold" target="_blank">Complete Office Hours Questionnaire</a>
    cta_text: Click here to add to your calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=NjY0cnBkazRkZWJobm1qYmxuanNxbWU5ZmQgbWlzYUBvcGVuYWkuY29t&tmsrc=misa%40openai.com
  - title: Project Owners Office Hours led by Jeeshan Chowdhury
    sub_title: Friday, April 10th 12pm-1pm PST | <a href="https://docs.google.com/spreadsheets/d/1_hKpejkq1Kf2Hs3dCTbcdJnHPx7LCLWDCIJec4PswJM/edit#gid=0" class="text-indigo-600 font-bold" target="_blank">Complete Office Hours Questionnaire</a>
    cta_text: Click here to add to your calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=MWo2ajM3ZHV0ZGRwZmVjZnJrM3Y3MnFtZmEgb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com
  - title: Project Owners Office Hours led by Radu Spineanu
    sub_title: Tuesday, April 14th 4pm-5pm PST | <a href="https://docs.google.com/spreadsheets/d/1z8jJdeHssfCSbsQ9HrmBebOdM1jCLk8nux7tJIUDCHY/edit#gid=0" class="text-indigo-600 font-bold" target="_blank">Complete Office Hours Questionnaire</a>
    cta_text: Click here to add to your calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=NjE4MXNhYWQ1ZmRyMDcwbWc1ZHJjZ3ZsdGsgbWlzYUBvcGVuYWkuY29t&tmsrc=misa%40openai.com
  - title: Live Webinar with Ambika Bumb
    sub_title: Thursday, April 16th 12pm-12:30pm PST | Ambika is a Health, Science and Technology Advisor focusing on Crisis Management and Strategy
    cta_text: Click here to add to your calendar
    cta_url: https://calendar.google.com/event?action=TEMPLATE&tmeid=NDZ0bGNzOG9rbDN0NWpkbHV0cm5zOHRqOTQgb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com
